.PHONY: all

all: proposed_question1.pdf proposed_question2.pdf proposed_question3.pdf proposed_question4.pdf proposed_question5.pdf proposed_question6.pdf

proposed_question1.pdf: proposed_question1.tex ../_bibliography/references.bib heading.tex
	pdflatex proposed_question1
	bibtex proposed_question1
	pdflatex proposed_question1
	pdflatex proposed_question1

proposed_question2.pdf: proposed_question2.tex ../_bibliography/references.bib heading.tex
	pdflatex proposed_question2
	bibtex proposed_question2
	pdflatex proposed_question2
	pdflatex proposed_question2

proposed_question3.pdf: proposed_question3.tex ../_bibliography/references.bib heading.tex
	pdflatex proposed_question3
	bibtex proposed_question3
	pdflatex proposed_question3
	pdflatex proposed_question3

proposed_question4.pdf: proposed_question4.tex ../_bibliography/references.bib heading.tex
	pdflatex proposed_question4
	bibtex proposed_question4
	pdflatex proposed_question4
	pdflatex proposed_question4

proposed_question5.pdf: proposed_question5.tex ../_bibliography/references.bib heading.tex
	pdflatex proposed_question5
	bibtex proposed_question5
	pdflatex proposed_question5
	pdflatex proposed_question5

proposed_question6.pdf: proposed_question6.tex ../_bibliography/references.bib heading.tex
	pdflatex proposed_question6
	bibtex proposed_question6
	pdflatex proposed_question6
	pdflatex proposed_question6
